title: Open Source for Government
description: A collaborative resource for government employees looking to participate in the open source community
url: http://ben.balter.com/open-source-for-government

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - vendor

collections:
  docs:
    output: true
    permalink: /:path/
